name: Run linter
on: [push]
jobs:
  my-job:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run linter
        uses: matlab-actions/run-command@v1
        with:
          command: addpath('tests'), lint_files();
